### ISSUE TITLE
Needs a crash fall-back

### ISSUE THREAD

**Issue by dainiusb** [rom1504/rbot#23]
I don't know is it just me but it's still very 'crashy'. I think that you should add something like crash fall-back so it would say something like 'Sorry...I had to stop doing this because I've messed up' instead of crashing. It's pretty annoying to start it again and again every minute.

**Comment by rom1504** [comment]
So, craft is now fixed in mineflayer, so some of these problems are solved.
I think it still crashes from time to time, the idea is to improve error handling ( #25 )

Still some problems remain, I'll open more precise issues when I identify these problems. If you still want to use the bot and find problems, please continue posting them in the issues ;)
